TiendaStark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('rest_vehiculo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from .views import administrar_pacientes, bitacora, home, administrar_productos, tienda, ficha, administrar_insumos
from .views import iniciar_sesion, registrar_usuario, cerrar_sesion
from .views import perfil_usuario, iniciar_pago, pago_exitoso
from .views import  index
from .views_poblar_bd import poblar_bd
from .views import administrar_pacientes,paciente,ficha_paciente, administrar_insumos, bitacora

urlpatterns = [
    path('', home, name="home"),
    path('index', index, name="index"),
    path('poblar_bd', poblar_bd, name="poblar_bd"),
    path('administrar_productos/<action>/<id>', administrar_productos, name="administrar_productos"),
    path('tienda', tienda, name="tienda"),
    path('ficha/<id>', ficha, name="ficha"),
    path('iniciar_sesion/', iniciar_sesion, name="iniciar_sesion"),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('registrar_usuario/', registrar_usuario, name="registrar_usuario"),
    path('password_cambiada/', TemplateView.as_view(template_name='core/password_cambiada.html'), name='password_cambiada'),
    path('cambiar_password/', auth_views.PasswordChangeView.as_view(template_name='core/cambiar_password.html', success_url='/password_cambiada'), name='cambiar_password'),
    path('perfil_usuario/', perfil_usuario, name="perfil_usuario"),
    path('iniciar_pago/', iniciar_pago, name="iniciar_pago"),
    path('pago_exitoso/', pago_exitoso, name="pago_exitoso"),
    path('administrar_pacientes/<action>/<id>', administrar_pacientes, name="administrar_pacientes"),
    path('pacientes/', paciente, name="pacientes"),
    path('ficha_paciente/<id>',ficha_paciente, name="ficha_paciente"),
    path('administrar_insumos/<action>/<id>', administrar_insumos, name="administrar_insumos"),
    path('bitacora/<action>/<id>',bitacora, name='bitacora'),
]

core/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name="Id de categoría")
    nombreCategoria = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre de la categoría")

    def __str__(self):
        return f"{self.idCategoria} - {self.nombreCategoria}"

class Vehiculo(models.Model):
    patente = models.CharField(max_length=6, primary_key=True, verbose_name="Patente")
    marca = models.CharField(max_length=80, blank=False, null=False, verbose_name="Marca vehículo")
    modelo = models.CharField(max_length=80, null=True, blank=True, verbose_name="Modelo")
    imagen = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="Imagen")
    precio = models.DecimalField(max_digits=35, decimal_places=2, null=False, blank=False, verbose_name="Precio")
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    

    def __str__(self):
        return f"{self.patente} - {self.marca}, {self.modelo}"

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=80, blank=True, null=True, verbose_name="Rut")
    direccion = models.CharField(max_length=80, blank=True, null=True, verbose_name="Dirección")

    def __str__(self):
        return f"{self.user.username} - {self.user.first_name} {self.user.last_name} ({self.user.email})"
    
class Paciente(models.Model):
    rut = models.CharField(max_length=12, primary_key=True, verbose_name="Rut")
    nombres = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombres")
    apellidos = models.CharField(max_length=80, blank=False, null=False, verbose_name="Apellidos")
    direccion = models.CharField(max_length=80, blank=False, null=False, verbose_name="Direccion")
    ciudad = models.CharField(max_length=80, blank=False, null=False, verbose_name="Ciudad")
    fnacimiento = models.DateField(blank=False, null=False, verbose_name="Fecha de nacimiento")
    edad = models.IntegerField(null=False, blank=False, verbose_name="Edad")
    sexo = models.CharField(max_length=1, blank=False, null=False, verbose_name="sexo")
    telefono = models.CharField(max_length=14, verbose_name="Teléfono")
    fingreso = models.DateField(blank=False, null=False, verbose_name="Fecha de ingreso")
    fsalida = models.DateField(blank=True, null=True, verbose_name="Fecha de salida")
    fresponsable = models.CharField(max_length=80, blank=False, null=False, verbose_name="Famliar responsable")
    tcontacto = models.CharField(max_length=14, verbose_name="Teléfono contacto")
    correo = models.CharField(max_length=70, null=False, blank=False, verbose_name="Correo")
    antmedicos = models.CharField(max_length=800, blank=True, null=True, verbose_name="Antecedentes Médicos")
    alergias = models.CharField(max_length=800, blank=True, null=True, verbose_name="Alergias")
    enfermedades = models.CharField(max_length=800, blank=True, null=True, verbose_name="Enfermedades Pre-existentes")
    medicamentos = models.CharField(max_length=800, blank=True, null=True, verbose_name="medicamentos uso diario")
    habitacion = models.CharField(max_length=3, blank=False, null=False, verbose_name="Nro. de Habitación")
    cuidados = models.CharField(max_length=30, blank=False, null=False, verbose_name="Nivel de cuidado")
    foto = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="foto")
    def __str__(self):
        return f"{self.nombres} - {self.apellidos}, {self.rut}"
    
class Insumo(models.Model):
    codigo = models.CharField(max_length=12, primary_key=True, verbose_name="Código")
    nombrein = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre")
    descripcion = models.TextField(max_length=80, verbose_name="Descripción")
    punitario = models.CharField(max_length=80, blank=False, null=False, verbose_name="Precio Unitario")
    cantidad = models.CharField(max_length=10, null=False, blank=False, verbose_name="Cantidad")
    fcompra = models.DateField(blank=False, null=False, verbose_name="Fecha de Compra")
    estado = models.CharField(max_length=30, blank=False, null=False, verbose_name="Estado")
    proveedor = models.CharField(max_length=80, blank=True, null=False, verbose_name="Proveedor")
    def __str__(self):
        return f"{self.codigo} - {self.nombrein}, {self.cantidad}, {self.estado}"
    
class Post(models.Model):
    residente = models.ForeignKey(Paciente, on_delete= models.CASCADE)
    titulo = models.CharField(max_length=60, null=False, blank=False, verbose_name="Titulo")
    encargado = models.CharField(max_length=60, null=False, blank=False, verbose_name="Encargado")
    fecha = models.DateField(blank=False, null=False,verbose_name="Fecha")
    hora = models.CharField(max_length=8, null=False, blank=False, verbose_name="Hora")
    anotacion = models.TextField(verbose_name="Anotacion")
    def __str__(self):
        return f"{self.residente} - {self.titulo}, {self.encargado},{self.fecha}"
    
    
    
    
    
    

core/views.py
from typing import Awaitable
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from .models import Paciente, Vehiculo, PerfilUsuario, Insumo, Post
from .forms import PacienteForm, VehiculoForm, IniciarSesionForm, InsumoForm
from .forms import RegistrarUsuarioForm, PerfilUsuarioForm, PacienteForm, PostForm
#from .error.transbank_error import TransbankError
#from transbank.webpay.webpay_plus.transaction import Transaction, WebpayOptions
import random

def home(request):
    return render(request, "core/home.html")

def index(request):
    return render(request, "core/index.html")

def iniciar_sesion(request):
    data = {"mesg": "", "form": IniciarSesionForm()}

    if request.method == "POST":
        form = IniciarSesionForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(home)
                else:
                    data["mesg"] = "¡La cuenta o la password no son correctos!"
            else:
                data["mesg"] = "¡La cuenta o la password no son correctos!"
    return render(request, "core/iniciar_sesion.html", data)

def cerrar_sesion(request):
    logout(request)
    return redirect(home)

def tienda(request):
    data = {"list": Vehiculo.objects.all().order_by('patente')}
    return render(request, "core/tienda.html", data)

#https://www.transbankdevelopers.cl/documentacion/como_empezar#como-empezar
#https://www.transbankdevelopers.cl/documentacion/como_empezar#codigos-de-comercio
#https://www.transbankdevelopers.cl/referencia/webpay

# Tipo de tarjeta   Detalle                        Resultado
#----------------   -----------------------------  ------------------------------
# VISA              4051885600446623
#                   CVV 123
#                   cualquier fecha de expiración  Genera transacciones aprobadas.
# AMEX              3700 0000 0002 032
#                   CVV 1234
#                   cualquier fecha de expiración  Genera transacciones aprobadas.
# MASTERCARD        5186 0595 5959 0568
#                   CVV 123
#                   cualquier fecha de expiración  Genera transacciones rechazadas.
# Redcompra         4051 8842 3993 7763            Genera transacciones aprobadas (para operaciones que permiten débito Redcompra y prepago)
# Redcompra         4511 3466 6003 7060            Genera transacciones aprobadas (para operaciones que permiten débito Redcompra y prepago)
# Redcompra         5186 0085 4123 3829            Genera transacciones rechazadas (para operaciones que permiten débito Redcompra y prepago)

@csrf_exempt
def iniciar_pago(request):
    print("Webpay Plus Transaction.create")
    buy_order = str(random.randrange(1000000, 99999999))
    session_id = request.user.username
    amount = random.randrange(10000, 1000000)
    return_url = 'http://127.0.0.1:8000/pago_exitoso/'

    # response = Transaction.create(buy_order, session_id, amount, return_url)
    commercecode = "597055555532"
    apikey = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"

    tx = Transaction(options=WebpayOptions(commerce_code=commercecode, api_key=apikey, integration_type="TEST"))
    response = tx.create(buy_order, session_id, amount, return_url)
    print(response['token'])

    perfil = PerfilUsuario.objects.get(user=request.user)
    form = PerfilUsuarioForm()

    context = {
        "buy_order": buy_order,
        "session_id": session_id,
        "amount": amount,
        "return_url": return_url,
        "response": response,
        "token_ws": response['token'],
        "url_tbk": response['url'],
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "email": request.user.email,
        "rut": perfil.rut,
        "direccion": perfil.direccion,
    }

    return render(request, "core/iniciar_pago.html", context)

@csrf_exempt
def pago_exitoso(request):

    if request.method == "GET":
        token = request.GET.get("token_ws")
        print("commit for token_ws: {}".format(token))
        commercecode = "597055555532"
        apikey = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
        tx = Transaction(options=WebpayOptions(commerce_code=commercecode, api_key=apikey, integration_type="TEST"))
        response = tx.commit(token=token)
        print("response: {}".format(response))

        user = User.objects.get(username=response['session_id'])
        perfil = PerfilUsuario.objects.get(user=user)
        form = PerfilUsuarioForm()

        context = {
            "buy_order": response['buy_order'],
            "session_id": response['session_id'],
            "amount": response['amount'],
            "response": response,
            "token_ws": token,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "email": user.email,
            "rut": perfil.rut,
            "direccion": perfil.direccion,
            "response_code": response['response_code']
        }

        return render(request, "core/pago_exitoso.html", context)
    else:
        return redirect(home)

@csrf_exempt
def ficha(request, id):
    data = {"mesg": "", "vehiculo": None}

    if request.method == "POST":
        if request.user.is_authenticated and not request.user.is_staff:
            return redirect(iniciar_pago)
        else:
            data["mesg"] = "¡Para poder comprar debe iniciar sesión como cliente!"

    data["vehiculo"] = Vehiculo.objects.get(patente=id)
    return render(request, "core/ficha.html", data)
 
@csrf_exempt
def administrar_productos(request, action, id):
    if not (request.user.is_authenticated and request.user.is_staff):
        return redirect(home)

    data = {"mesg": "", "form": VehiculoForm, "action": action, "id": id, "formsesion": IniciarSesionForm}

    if action == 'ins':
        if request.method == "POST":
            form = VehiculoForm(request.POST, request.FILES)
            if form.is_valid:
                try:
                    form.save()
                    data["mesg"] = "¡El vehículo fue creado correctamente!"
                except:
                    data["mesg"] = "¡No se puede crear dos vehículos con la misma patente!"

    elif action == 'upd':
        objeto = Vehiculo.objects.get(patente=id)
        if request.method == "POST":
            form = VehiculoForm(data=request.POST, files=request.FILES, instance=objeto)
            if form.is_valid:
                form.save()
                data["mesg"] = "¡El vehículo fue actualizado correctamente!"
        data["form"] = VehiculoForm(instance=objeto)

    elif action == 'del':
        try:
            Vehiculo.objects.get(patente=id).delete()
            data["mesg"] = "¡El vehículo fue eliminado correctamente!"
            return redirect(administrar_productos, action='ins', id = '-1')
        except:
            data["mesg"] = "¡El vehículo ya estaba eliminado!"

    data["list"] = Vehiculo.objects.all().order_by('patente')
    return render(request, "core/administrar_productos.html", data)

def registrar_usuario(request):
    if request.method == 'POST':
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            user = form.save()
            rut = request.POST.get("rut")
            direccion = request.POST.get("direccion")
            PerfilUsuario.objects.update_or_create(user=user, rut=rut, direccion=direccion)
            return redirect(iniciar_sesion)
    form = RegistrarUsuarioForm()
    return render(request, "core/registrar_usuario.html", context={'form': form})

def perfil_usuario(request):
    
    data = {"mesg": "", "form": PerfilUsuarioForm}

    if request.method == 'POST':
        form = PerfilUsuarioForm(request.POST)
        if form.is_valid():
            user = request.user
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.email = request.POST.get("email")
            user.save()
            perfil = PerfilUsuario.objects.get(user=user)
            perfil.rut = request.POST.get("rut")
            perfil.direccion = request.POST.get("direccion")
            perfil.save()
            data["mesg"] = "¡Sus datos fueron actualizados correctamente!"

    perfil = PerfilUsuario.objects.get(user=request.user)
    form = PerfilUsuarioForm()
    form.fields['first_name'].initial = request.user.first_name
    form.fields['last_name'].initial = request.user.last_name
    form.fields['email'].initial = request.user.email
    form.fields['rut'].initial = perfil.rut
    form.fields['direccion'].initial = perfil.direccion
    data["form"] = form
    return render(request, "core/perfil_usuario.html", data)

@csrf_exempt
def administrar_pacientes(request, action, id):
    if not (request.user.is_authenticated and request.user.is_staff):
        return redirect(home)

    data = {"mesg": "", "form": PacienteForm, "action": action, "id": id, "formsesion": IniciarSesionForm}

    if action == 'ins':
        if request.method == "POST":
            form = PacienteForm(request.POST, request.FILES)
            if form.is_valid:
                try:
                    form.save()
                    data["mesg"] = "¡La ficha paciente se creo correctamente!"
                except:
                    data["mesg"] = "¡No se pueden generar dos fichas con el mismo rut!"

    elif action == 'upd':
        objeto = Paciente.objects.get(rut=id)
        if request.method == "POST":

core/templates/core/administrar_pacientes.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'core/css/forms.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Administrar Residentes</h1>
{% if form %}
<form method="POST" action="" enctype="multipart/form-data" id="formulario">
    <div class="form-group">
        {% csrf_token %} {{ form.as_ul }}
        {% if action == 'upd'  %}
            <script>
                $(document).ready(function() {
                    $('#id_paciente').attr('readonly', true);
                });
            </script>
        {% endif %}

    </div>
    <input type="submit" class="btn btn-primary btnwidth" id="id_guardar" value="Guardar">
    <a class="btn btn-success btnwidth" href="{% url 'administrar_pacientes' 'ins' -1 %}">Nuevo</a>
    {% if id != '-1' %}
    <a class="btn btn-danger btnwidth" href="{% url 'administrar_pacientes' 'del' id %}">Eliminar</a>
    {% endif %}
    <a class="btn btn-info btnwidth" href="{% url 'home' %}">Inicio</a>
    {% if mesg %}
    <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
    {% endif %}
</form>
{% endif %}
{% if list %}
<table id="tabla_datos">
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Rut</th>
            <th>Edad</th>
            <th>Fecha de Ingreso</th>
            <th>Fecha de Salida</th>
            <th>Habitación</th>
            <th class="titulo_boton">Editar</th>
            <th class="titulo_boton">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for pa in list %}
        <tr>
            <td>{{ pa.nombres }}</td>
            <td>{{ pa.apellidos }}</td>
            <td>{{ pa.rut }}</td>
            <td>{{ pa.edad }}</td>
            <td>{{ pa.fingreso }}</td>
            <td>{{ pa.fsalida }}</td>
            <td>{{ pa.habitacion }}</td>
            <td><a href="{% url 'administrar_pacientes' 'upd' pa.rut %}" 
                class="btn btn-primary btn-sm boton_chico">Editar</a></td>
            <td><a href="{% url 'administrar_pacientes' 'del' pa.rut %}" 
                class="btn btn-danger btn-sm boton_chico">Eliminar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock content %}

core/templates/core/administrar_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'core/css/forms.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Administrar Productos</h1>
{% if form %}
<form method="POST" action="" enctype="multipart/form-data" id="formulario">
    <div class="form-group">
        {% csrf_token %} {{ form.as_ul }}
        {% if action == 'upd'  %}
            <script>
                $(document).ready(function() {
                    $('#id_patente').attr('readonly', true);
                });
            </script>
        {% endif %}

    </div>
    <input type="submit" class="btn btn-primary btnwidth" id="id_guardar" value="Guardar">
    <a class="btn btn-success btnwidth" href="{% url 'administrar_productos' 'ins' -1 %}">Nuevo</a>
    {% if id != '-1' %}
    <a class="btn btn-danger btnwidth" href="{% url 'administrar_productos' 'del' id %}">Eliminar</a>
    {% endif %}
    <a class="btn btn-info btnwidth" href="{% url 'home' %}">Inicio</a>
    {% if mesg %}
    <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
    {% endif %}
</form>
{% endif %}
{% if list %}
<table id="tabla_datos">
    <thead>
        <tr>
            <th>Patente</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Imagen</th>
            <th>Precio</th>
            <th>Categoría</th>
            <th class="titulo_boton">Editar</th>
            <th class="titulo_boton">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for ve in list %}
        <tr>
            <td>{{ ve.patente }}</td>
            <td>{{ ve.marca }}</td>
            <td>{{ ve.modelo }}</td>
            <td><img src="/media/{{ ve.imagen }}" class="mini_auto" alt=""></td>
            <td>{{ ve.precio }}</td>
            <td>{{ ve.categoria }}</td>
            <td><a href="{% url 'administrar_productos' 'upd' ve.patente %}" 
                class="btn btn-primary btn-sm boton_chico">Editar</a></td>
            <td><a href="{% url 'administrar_productos' 'del' ve.patente %}" 
                class="btn btn-danger btn-sm boton_chico">Eliminar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock content %}

core/templates/core/administrar_tienda.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Bootstrap E-commerce Templates</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<!--[if ie]><meta content='IE=8' http-equiv='X-UA-Compatible'/><![endif]-->
		
		<!-- bootstrap -->
		<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">      
		<link href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">		
		<link href="themes/css/bootstrappage.css" rel="stylesheet"/>
		<link href="themes/css/adicion.css" rel="stylesheet"/>
		
		<!-- global styles -->
		<link href="themes/css/main.css" rel="stylesheet"/>
		<link href="themes/css/jquery.fancybox.css" rel="stylesheet"/>
				
		<!-- scripts -->
		<script src="themes/js/jquery-1.7.2.min.js"></script>
		<script src="bootstrap/js/bootstrap.min.js"></script>				
		<script src="themes/js/superfish.js"></script>	
		<script src="themes/js/jquery.scrolltotop.js"></script>
		<script src="themes/js/jquery.fancybox.js"></script>
		<!--[if lt IE 9]>			
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
			<script src="js/respond.min.js"></script>
		<![endif]-->
		<link rel="icon" type="image/png" href="themes/images/logo.png">
	</head>
    <body>		
		<div id="top-bar" class="container">
			<div class="row container-fluid">
					<ul class="user-menu">
						<a href="index.html" class="logo pull-left"><img src="themes/images/logo.png" class="site_logo" alt=""></a>			
						<li><a href="index.html">Inicio</a></li>
						<li><a href="administrar_tienda.html">Administrar Tienda</a></li>
						<li><a href="sobre_nosotros.html">Nosotros</a></li>
						<li><a href="index.html">Cerrar Sesión</a></li>
						<li><a href="registro_ventas.html">registro ventas</a></li>		
					</ul>
			</div>
		</div>


		<div id="wrapper" class="container">
			</section>
			<br>
			<div>
				<section class="main-content">				
					<div class="row">
						<div class="span9">					
							<h4 class="title"><span class="text"><strong>ADMINISTRAR</strong></span></h4>
							<div class="adicion">
								<p class="accordion-toggle" data-toggle="collapse" href="#collapseOne">Opciones</p>
							</div>
								<div  id="collapseOne" class="accordion-body in collapse">
									<div class="control-group">
										<button><a href="maestro_usuario.html">mantenedor de usuario</a></button>
									</div>								<div class="control-group">
										<button><a href="maestro_producto.html">mantenedor de producto</a></button>
									</div>								<div class="control-group">
										<button><a href="registro_ventas.html">historial de ventas</a></button>
									</div>								<div class="control-group">
										<button><a href="inventario.html">mantenedor de bodega</a></button>
									</div>
									</div>								<div class="control-group">
										<button><a href="registro_ventas.html">Registro de ventas</a></button>
									</div>
								</div>
						</div>
					</div>
				</section>
			</div>			
			<section id="footer-bar">
				<div class="row">
					<div class="span3 abajo">
						<h4>Navegar</h4>
						<ul class="nav">
							<li><a href="index.html">Inicio</a></li>  
							<li><a href="sobre_nosotros.html">Sobre nosotros</a></li>
							<li><a href="registro.html">Registrate</a></li>
							<li><a href="login.html">Inicio de sesion</a></li>							
						</ul>					
					</div>						
				</div>	
			</section>
		</div>
		<script src="themes/js/common.js"></script>
		<script>
			$(function () {
				$('#myTab a:first').tab('show');
				$('#myTab a').click(function (e) {
					e.preventDefault();
					$(this).tab('show');
				})
			})
			$(document).ready(function() {
				$('.thumbnail').fancybox({
					openEffect  : 'none',
					closeEffect : 'none'
				});
				
				$('#myCarousel-2').carousel({
                    interval: 2500
                });								
			});
		</script>
    </body>
</html>

core/templates/core/create.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Ejemplos Webpay Plus - Crear Transaccion</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body class="container">
    <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Ejemplo Webpay Plus - Crear Transaccion</a></li>
    <li class="breadcrumb-item active" aria-current="page">Step: <strong>Create Transaction</strong></li>
    </ol>
    </nav>

    <div class="alert alert-warning" role="alert">
    <h3>request</h3>
        {% for k, v in request.items %}
            {{ k }} = {{ v }},
        {% endfor %}
</div>
    <div class="alert alert-primary" role="alert">
    <h3>result</h3>
    {{ response }}
</div>
<br>
    <div class="alert alert-success" role="alert">
        <p>Sesion iniciada con exito en Webpay patpass</p>
    </div>
<br>
<form action="{{ response.url }}" method="POST">
<input type="hidden" name="token_ws" value="{{ response.token }}">
<input type="submit" value="Ejecutar Pago con Webpay">
</form>
<br>

<a href="/">&laquo; volver a index</a>
</body>
</html>

core/templates/core/iniciar_sesion.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/iniciar_sesion.css'%}" rel="stylesheet">
{% endblock %}

{% block content %}
    <h1>Iniciar Sesión</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 borde_formulario">
                <form method="POST" action="" enctype="multipart/form-data" id="formulario">
                    <div class="centrar">
                        {% csrf_token %} {{ form.as_p }}
                        <input type="submit" class="btn btn-primary" value="Ingresar">
                        {% if mesg %}
                        <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}